// Code generated by hand. DO NOT EDIT.

// tests
package blame_test

import (
	"errors"
	"runtime"
	"strings"
	"testing"

	"github.com/ARC5RF/go-blame"
)

var o0m = errors.New("O0 error message")

func baz_0() error { return blame.O0(o0m).WithAdditionalContext("from baz_0") }
func biz_0() error { return blame.O0(baz_0()).WithAdditionalContext("from biz_0") }
func bar_0() error { return blame.O0(biz_0()).WithAdditionalContext("from bar_0") }
func foo_0() error { return blame.O0(bar_0()).WithAdditionalContext("from foo_0") }

var expect_0_parts = []string{
	"BUILD_EXPECT_0:17 github.com/ARC5RF/go-blame_test.baz_0",
	"	from baz_0",
	"",
	"BUILD_EXPECT_0:18 github.com/ARC5RF/go-blame_test.biz_0",
	"	from biz_0",
	"",
	"BUILD_EXPECT_0:19 github.com/ARC5RF/go-blame_test.bar_0",
	"	from bar_0",
	"",
	"BUILD_EXPECT_0:20 github.com/ARC5RF/go-blame_test.foo_0",
	"	from foo_0",
	"",
	"O0 error message",
}
var expect_0 = strings.ReplaceAll(strings.Join(expect_0_parts, "\n"), "BUILD_EXPECT_0", fname)

func TestO0(t *testing.T) {
	got := foo_0().Error()
	if got != expect_0 {
		t.Log(got)
		t.Log(expect_0)
		t.Fail()
		return
	}
}

var o1m = errors.New("O1 error message")

func baz_1() (int, error) {
	v, e := blame.O1(1, o1m)
	return v, e.WithAdditionalContext("from baz_1")
}
func biz_1() (int, error) { v, e := blame.O1(baz_1()); return v, e.WithAdditionalContext("from biz_1") }
func bar_1() (int, error) { v, e := blame.O1(biz_1()); return v, e.WithAdditionalContext("from bar_1") }
func foo_1() (int, error) { v, e := blame.O1(bar_1()); return v, e.WithAdditionalContext("from foo_1") }

var expect_1_parts = []string{
	"BUILD_EXPECT_1:52 github.com/ARC5RF/go-blame_test.baz_1",
	"	from baz_1",
	"",
	"BUILD_EXPECT_1:55 github.com/ARC5RF/go-blame_test.biz_1",
	"	from biz_1",
	"",
	"BUILD_EXPECT_1:56 github.com/ARC5RF/go-blame_test.bar_1",
	"	from bar_1",
	"",
	"BUILD_EXPECT_1:57 github.com/ARC5RF/go-blame_test.foo_1",
	"	from foo_1",
	"",
	"O1 error message",
}
var expect_1 = strings.ReplaceAll(strings.Join(expect_1_parts, "\n"), "BUILD_EXPECT_1", fname)

func TestO1(t *testing.T) {
	_, got := foo_1()
	if got.Error() != expect_1 {
		t.Log(got)
		t.Log(expect_1)
		t.Fail()
		return
	}
}

//TODO better 0-N tests (it is currently assumed that O0 and O1 cover all cases of N)

func n() string {
	_, fname, _, ok := runtime.Caller(0)
	if !ok {
		return ""
	}
	return fname
}

var fname = n()
